---

- name: Update package list (apt update)
  apt:
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Upgrade packages (apt upgrade)
  apt:
    upgrade: yes
  when: ansible_os_family == 'Debian'
