- name: Install DHCP Server
  apt:
    name: isc-dhcp-server
    state: present

- name: Set up dhcpd.conf
  template:
    src: dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf
  notify: restart isc-dhcp-server

- name: Configure INTERFACESv4
  lineinfile:
    path: /etc/default/isc-dhcp-server
    regexp: '^INTERFACESv4='
    line: 'INTERFACESv4="{{ dhcp_interface }}"'
    create: yes
  notify: restart isc-dhcp-server
