- name: Apply and Restart WireGuard
  command: "sudo wg-quick up wg0"
  async: 300
  poll: 0
  ignore_errors: true
  notify: Restart WireGuard

- name: Restart WireGuard
  systemd:
    name: "wg-quick@wg0"
    state: restarted
    enabled: true
