---

- name: Install DNS Server
  apt:
    name: bind9
    state: present

- name: Configure named options
  template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
  notify: Restart bind9

- name: Configure named local
  template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
  notify: Restart bind9

- name: Configure Site 1 Zone
  template:
    src: db.site1.j2
    dest: /etc/bind/db.site1
  when: inventory_hostname in groups['site1']
  notify: Restart bind9

- name: Configure Site 2 Zone
  template:
    src: db.site2.j2
    dest: /etc/bind/db.site2
  when: inventory_hostname in groups['site2']
  notify: Restart bind9
